---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  path: ./kubernetes/apps/cert-manager/app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-cert-manager-issuers
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  dependsOn:
    - name: apps-cert-manager
    - name: apps-security-system-external-secrets-stores
  path: ./kubernetes/apps/cert-manager/issuers
