---
apiVersion: v1
kind: Secret
metadata:
  name: ${APPNAME}-restic
  namespace: ${APPNAME}
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${SECRET_VOLSYNC_R2_REPO}/${APPNAME}
  RESTIC_PASSWORD: ${SECRET_VOLSYNC_PASSWORD}
  AWS_ACCESS_KEY_ID: ${SECRET_VOLSYNC_R2_ID}
  AWS_SECRET_ACCESS_KEY: ${SECRET_VOLSYNC_R2_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APPNAME}-restic
  namespace: ${APPNAME}
spec:
  sourcePVC: ${APPNAME}-data
  trigger:
    schedule: "0 6 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: ${APPNAME}-restic
    cacheCapacity: 2Gi
    volumeSnapshotClassName: block
    storageClassName: block
    moverSecurityContext:
      runAsUser: &uid ${APP_UID_APPNAME}
      runAsGroup: *uid
      fsGroup: *uid
    retain:
      daily: 14
      within: 7d
