---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-core-external-secrets-app
  namespace: flux-system
spec:
  path: ./kubernetes/deployments/core/external-secrets/app
  dependsOn: []
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-core-secrets-op
  namespace: flux-system
spec:
  path: ./kubernetes/deployments/core/external-secrets/stores
  dependsOn:
    - name: 1-core-external-secrets-app
