---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-kube-system-cilium
  namespace: flux-system
  labels:
    kustomization.flux.home.arpa/name: "cilium"
    kustomization.flux.home.arpa/helmpatches: "false"
spec:
  path: ./kubernetes/apps/kube-system/cilium/app
  dependsOn: []
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-kube-system-cilium-config
  namespace: flux-system
  labels:
    kustomization.flux.home.arpa/name: "cilium"
    kustomization.flux.home.arpa/helmpatches: "false"
spec:
  path: ./kubernetes/apps/kube-system/cilium/config
  dependsOn:
    - name: apps-kube-system-cilium
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: apps-kube-system-cilium-netpols
#   namespace: flux-system
#   labels:
#     kustomization.flux.home.arpa/name: "cilium"
#     kustomization.flux.home.arpa/helmpatches: "false"
# spec:
#   path: ./kubernetes/apps/kube-system/cilium/netpols
#   dependsOn:
#     - name: apps-kube-system-cilium
