---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
  namespace: security-system
type: Opaque
stringData:
  token: "${OP_CONNECT_TOKEN}"
  1password-credentials.json: "${OP_CREDENTIALS_JSON}"
