---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - hr.yaml
  - externalsecret.yaml
configMapGenerator:
  - name: cloudflared-configmap
    files:
      - ./configs/config.yaml
generatorOptions:
  disableNameSuffixHash: true
