---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-security-system-external-secrets
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security-system/external-secrets/app
  dependsOn:
    - name: apps-security-system-onepassword-connect
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-security-system-external-secrets-stores
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security-system/external-secrets/stores
  dependsOn:
    - name: apps-security-system-external-secrets
