---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-external-secrets-app
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security-system/external-secrets/app
  dependsOn:
    - name: core-onepassword-connect-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-external-secrets-stores
  namespace: flux-system
spec:
  path: ./kubernetes/apps/security-system/external-secrets/stores
  dependsOn:
    - name: core-external-secrets-app
