---
clusterName: ${CLUSTER_NAME}
talosVersion: ${TALOS_VERSION}
kubernetesVersion: ${KUBERNETES_VERSION}
endpoint: "https://${DNS_CONTROLPLANE_FQDN}:6443"
domain: ${DNS_CLUSTER_DN}

allowSchedulingOnMasters: true

cniConfig:
  name: none

additionalMachineCertSans:
  - ${IP_CLUSTER_VIP}
  - ${DNS_CONTROLPLANE_FQDN}

additionalApiServerCertSans:
  - ${IP_CLUSTER_VIP}

clusterPodNets:
  - ${IP_CIDR_K8S_POD}

clusterSvcNets:
  - ${IP_CIDR_K8S_SVC}

nodes:
  - hostname: kube-prod-control-01
    ipAddress: ${IP_CONTROL_01}
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        addresses:
          - "${IP_CONTROL_01}/24"

  - hostname: kube-prod-control-02
    ipAddress: ${IP_CONTROL_02}
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        addresses:
          - "${IP_CONTROL_02}/24"

  - hostname: kube-prod-control-03
    ipAddress: ${IP_CONTROL_03}
    installDisk: /dev/sda
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        vlans:
        addresses:
          - "${IP_CONTROL_03}/24"

  - hostname: kube-prod-worker-01
    ipAddress: ${IP_WORKER_01}
    controlPlane: false
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        addresses:
          - "${IP_WORKER_01}/24"

patches:
  - |-
    - op: add
      path: /cluster/extraManifests
      value:
        - "https://raw.githubusercontent.com/mologie/talos-vmtoolsd/master/deploy/unstable.yaml"
        - "https://raw.githubusercontent.com/freeblazin/home-ops/main/kubernetes/bootstrap/csr-approver/csr-approver.yaml"
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        feature-gates: CronJobTimeZone=true,GracefulNodeShutdown=true,ServerSideApply=true
        rotate-server-certificates: "true"
    - op: add
      path: /machine/network/nameservers
      value:
        - ${IP_HOME_DNS_1}
        - ${IP_HOME_DNS_2}
    - op: add
      path: /machine/network/disableSearchDomain
      value: true
    - op: add
      path: /machine/network/interfaces/0/mtu
      value: 1500
    - op: add
      path: /machine/network/interfaces/0/dhcp
      value: false
    - op: add
      path: /machine/network/interfaces/0/routes
      value:
        - network: 0.0.0.0/0
          gateway: ${IP_GATEWAY_K8S_NODE}
    - op: add
      path: /machine/time
      value:
        disabled: false
        servers:
          - ${IP_NTP_SERVER}
    - op: add
      path: /machine/features
      value:
        kubePrism:
          enabled: true
          port: 7445
    - op: add
      path: /cluster/proxy
      value:
        disabled: true

controlPlane:
  patches:
    - |-
      - op: add
        path: /machine/network/interfaces/0/vip
        value:
          ip: ${IP_CLUSTER_VIP}
      - op: add
        path: /cluster/apiServer/extraArgs
        value:
          feature-gates: CronJobTimeZone=true,GracefulNodeShutdown=true,ServerSideApply=true
