---
ingress:
  - hostname: "${DNS_PUBLIC_ROOT}"
    service: http://nginx-external-controller.ingress-nginx.svc.cluster.local
    originRequest:
      originServerName: "external.${DNS_PUBLIC_ROOT}"
  
  - hostname: "*.${DNS_PUBLIC_ROOT}"
    service: http://nginx-external-controller.ingress-nginx.svc.cluster.local
    originRequest:
      originServerName: "external.${DNS_PUBLIC_ROOT}"

  - service: http_status:404
