---
ingress:
  - hostname: "*.${DNS_PUBLIC_ROOT}"
    service: https://nginx-external-controller.ingress-nginx.svc.cluster.local:443
    originRequest:
      originServerName: "ingress.${DNS_PUBLIC_ROOT}"

  - service: http_status:404
