---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-network-system-echo-server
  namespace: flux-system
spec:
  targetNamespace: network-system
  path: ./kubernetes/apps/network-system/echo-server/app
  dependsOn:
    - name: apps-ingress-nginx
