---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-core-ingress-deps
  namespace: flux-system
spec:
  path: ./kubernetes/deployments/core/ingress/_deps/app
  dependsOn: []
