---
# yaml-language-server: $schema=https://kubernetes-schemas.raspbernetes.com/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app kubelet-csr-approver
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: *app
      version: 1.0.5
      sourceRef:
        kind: HelmRepository
        name: postfinance-charts
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: kubelet-csr-approver-values
