---
autoDirectNodeRoutes: true

bgpControlPlane:
  enabled: true

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

cluster:
  name: ${CLUSTER_NAME}
  id: ${CONFIG_CILIUM_CLUSTER_ID}

containerRuntime:
  integration: containerd

hubble:
  enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA,
      - drop
      - tcp
      - flow
      - http
      - icmp
      - port-distribution
  relay:
    enabled: true
    rollOutPods: true
  peerService:
    clusterDomain: "${DNS_CLUSTER_DN}"
  tls:
  enabled: true
  auto:
    enabled: true
    method: "helm"
    certValidityDuration: 3650
  ui:
    enabled: true
    rollOutPods: true
    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - "${APP_DNS_HUBBLE}"
      tls:
        - hosts:
            - "${APP_DNS_HUBBLE}"

ipam:
  mode: kubernetes

ipv4NativeRoutingCIDR: ${IP_POD_CIDR_V4}

k8sServiceHost: ${IP_CLUSTER_VIP}

k8sServicePort: 6443

kubeProxyReplacement: true

kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

l7Proxy: true

loadBalancer:
  algorithm: maglev
  mode: dsr

localRedirectPolicy: true

operator:
  enabled: true
  rollOutPods: true

rollOutCiliumPods: true

securityContext: # required for Talos
  privileged: true
  capabilities:
    ciliumAgent: "{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
    cleanCiliumState: "{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"

tunnel: disabled