---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: kube-dev-secrets
    namespace: flux-system
    envs:
      - ./secrets.sops.env
  - name: kube-dev-vars
    namespace: flux-system
    envs:
      - ./vars.sops.env
generatorOptions:
  disableNameSuffixHash: true
