---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s
  namespace: flux-system
spec:
  type: oci
  interval: 1h
  timeout: 3m0s
  url: oci://ghcr.io/bjw-s/helm
