---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../vars/
  - flux-install.yaml
  - flux-repo.yaml
  - app-template-repo.yaml
  - ../../../apps/kube-system/
  - ../../../apps/ingress-nginx/
  - ../../../apps/security-system/
  - ../../../apps/network-system/
  - ../../../apps/cert-manager/
