---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../vars/
  - flux-install.yaml
  - flux-repo.yaml
  - ../../../deployments/core/kubelet-csr-approver/
  - ../../../deployments/core/_networking/cilium/
  - ../../../deployments/core/ingress/_deps/
  - ../../../deployments/core/ingress/ingress-nginx/
  - ../../../deployments/core/external-secrets
