apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: kube-prod-secrets
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:8QJ25/0ZxDCHM2OQW2C8PTU4amDl6t6Kb57qbyuFPTIJQh1xDiH2TLQRP/R38lIHAnNC7Db1zQE1Cro=,iv:6y4pzGxj1auyf0GyEWyNvUxztby0SmjgsFkCvlyll80=,tag:QupkqQF2U3W5go2BKApdJA==,type:str]
    GITHUB_USER: ENC[AES256_GCM,data:F8e0wrMiSjJPQ0wg3Tn6p6tbn+mryz79R9z0THmbic8oFRSH0fe2QAMKWyxylaG6O5kqlGIPkJvu,iv:vuWG9nLASDQsPCHvVw9QXWVLAj9PcenEQgC/QsiWpGU=,tag:1HFwc1eNtsbGYl5S9AUx5A==,type:str]
    GOVC_URL: ENC[AES256_GCM,data:3hUbfPhL2H7AX5KbeoW6mcT7PnUGwVHoqWDexNMJ/klAiUiL84uxEe4ZO0GD+BniC9okuhwGQJnm5Kg1hsV6HfTa138lABS4Xj8=,iv:X0AIUJ2lRKXjMk/rvjM4P1Z2eFtxByBelLdM6r/9ulQ=,tag:G6wtnbsoaVXOJ4l6M0mDOQ==,type:str]
    GOVC_USERNAME: ENC[AES256_GCM,data:HHwHkUx10mSVKH/oSKjYiGJyGPIPyUhMJz3Mv3k7TMIABjQ4roD4IA1a3UgW//7Lui15zS0kU1c+Kt5HWRZFUKcb82DdHg==,iv:EBlAG9J42b2lWIcetLibmDLP8ac+dSljaX6ikEgyqng=,tag:ng7BVjZsifZ41rwVgl8vZA==,type:str]
    GOVC_PASSWORD: ENC[AES256_GCM,data:WgfLPv6Lw7uMwv2gmFsLUPIuwvNDYS5ZtKJJHBiqNO1vQwR8sfQ1wBv/cbMlZ9d2Gv1Ah89w+1XogJl/eF5XGgJwujA+/Q==,iv:Fx+Yx/CU/i3bRRo3woczCMoeftjOGE0kXkGzE+lhrW4=,tag:n1veeKX0mdeGFQyU6f2X2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1skatly42g7vng3twta22kdlvzg98p3p5zk7rzn285pncxkzzu3usvp7gvh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UlladEhJNDViOWRWbGRp
            b2MzclJrd0J4VmY3cHZNUUIrVGQyME9TMmpRCllmQkFsVFBOWngrdzFVM2MyTXc2
            cmFNVU1mN0gvUFdQSkRkZWtQK1p2SncKLS0tIDRLTldmOG5TNlFHd0M4R3dVYnEv
            L1pQYTBlb2s4bGhQMkt2TlhXYS9UZ2MKLNI/hf8eEbTcpzfb/K6iqd8nFk5Z0ytj
            alC2pfTX0YYrq+PVKtB2muDaeMyRFHZyKPvbUJnlK5rCj3gvYgT1pQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-20T14:11:24Z"
    mac: ENC[AES256_GCM,data:mHYqgvlmkTLABPnLHwuy0hm26igPjqm0tVXEmj35snvtUKe5AHuB25jtrL3qIc0TCgFJ7IYDj2otoyoNIlKGnnORGum2ZkwYNgWvCvK821xbrWcVG7JQ9T4VBokPMmWx2c3z8Z8H7TWztSaKbc1dmpHs/pu0L3O9ksfd8ruULSY=,iv:tL+/xVe/fxoZiJvhG33ZtHthj/74UfFHLR0G30lmROY=,tag:4Upop7UNlWFIBwM1ZfVaew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
