apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: kube-prod-secrets
stringData:
    GITHUB_TOKEN: ENC[AES256_GCM,data:OJP7YmtBy037JOi8FDUd8YW0PC97SOsC7IDG1DSZVWcRnnfwLBORUdOGv/rFjSC5kWYNFgyPBqAxI2I=,iv:ObmRhXlqesQVcWMYRMn3kGm1sFuPAHdD8yH7XcLj8CM=,tag:3ltsXbQv0/I8nFmrlSSlcw==,type:str]
    GITHUB_USER: ENC[AES256_GCM,data:YjSHH3ZBhr5WF+TwekMvDyMiBUcH3JvWzAszQ504Ty4Uc7E+Rs6fkqFhRM3fEeBSPLBaqxvuvO5m,iv:A1X/xeikIItHWgnbcthOYp9QnSyASSreqdqM4DxxCKU=,tag:FBZBxEkx1kDBiie+1J7L0A==,type:str]
    GOVC_URL: ENC[AES256_GCM,data:rEhjSbQg09mfK3dr7i9R5ZPq6er+yjZ3r6dm6M7IIIx2GgFfIl0U4OEjkTh1zAnbS2qkocniZpTUCwJavoliVY9KuBEPGPCDxjM=,iv:TLg5IdLs18Z08HrfDIZOMobPCacUw0r9ytCVwwRqWXk=,tag:pbQVLAB1ALgBTpD1AB/TwA==,type:str]
    GOVC_USERNAME: ENC[AES256_GCM,data:oP+4S1S1vriKcnSdwQgbUxpwB6f4sncp5ozVL2F7jA4iW4aX/4f+phmSs9kvGxFzTsz+oVBj+teTD3niiK9CYSl6W3P1DQ==,iv:CB9FFCiCMYYZmMrlAno+R5IhEXWKW6kvxnxXbvhNMFM=,tag:GFhp46QOXMdn71xgAIL/QA==,type:str]
    GOVC_PASSWORD: ENC[AES256_GCM,data:UoRtw6NXpxWBIxrHvxcvlfwaRd3wJ+/9HB7NML6fpldKYZktwHrEpJvKsWyj5lbxIh+d8Q9tD5pXNgG7UAMIowOI80k31w==,iv:Rsi1DdKmFiDiTki+1A27goEtU4x0cjPFemKZ/dACZ2E=,tag:OQvPQada4x/7g2v4Ah/c5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1skatly42g7vng3twta22kdlvzg98p3p5zk7rzn285pncxkzzu3usvp7gvh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6N3F2QzNkSVpJWnhhUWVY
            SWkwN0hhZXJqZnhQS0x2WUVIT3pkUkVZa3l3CitTVUhDd1pXcmZ0cStDdDRzeFox
            WkF6SGlrcEtmS2UyQ2p2N3NZZGsvc3MKLS0tIG50blA5Z2xTRUF3TU4yZ2JVSG9w
            RDcvWXp2UUlQaVRWd3hEdDBGb2ZNUEkK+8nvDkywAvxFpB/b+KM1RWedURCSW9Lc
            uDWYVGCHXSPlAMzijr2c1/A0yy9Yy22bkDsr1C0F1dyJZmk6MIJDIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-29T22:16:46Z"
    mac: ENC[AES256_GCM,data:stbDTppKi/oMUH5DF7IT5A9baLM2zh8Zl12Vq9H48vPKKvpGuQst8ao6dAKtCOLlGZIFH+FOp2CGBdJaEK1BNyhuYeXxPiv7yqXyDgRAYJaaFXGLWMQIlEf259C41M9GnUU86zvowZj5Ht3BzPJaX/0igIqZRkuTBs+E5CdTeUg=,iv:bLXpdOUrROpaicevYWJY9Wi0a8bumW6z+cFu0cgnZwE=,tag:1XFXj7XhcaAI5VdBjrd6iQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
