apiVersion: v1
kind: Secret
metadata:
  namespace: flux-system
  name: kube-prod-vars
stringData:
  TALOS_VERSION: ENC[AES256_GCM,data:RPzk+SBg,iv:wltR1jgqXcASBLHoqbNxguse2hWwH8bONmv+GJUMDDw=,tag:6xUuPDGTxCnyAK+Z1vWa+Q==,type:str]
  KUBERNETES_VERSION: ENC[AES256_GCM,data:wuq3eg2QFQ==,iv:HjyyToFffgs2G1wyThfraa5Vzx/A0cASeX8bY2nK1Og=,tag:rVslhlNa4U1tpzgvLxAfhQ==,type:str]
  CLUSTER_NAME: ENC[AES256_GCM,data:+cIrGxGJNvpI,iv:SQ8iolAe88bbjrU5oNGOzYS1QTbOuaIMa0/GLu+9gMk=,tag:GkPcZEEG7dQP1tyYb3AU7A==,type:str]
  CONFIG_CILIUM_CLUSTER_ID: ENC[AES256_GCM,data:5w==,iv:FBj4GiX3AAhXcF8/SbXobsVSl8yWhVcGDWLXfAW7NnQ=,tag:C8wsN3mAWtTE6hIL9a+xng==,type:str]
  CONFIG_CONTROL_CPU: ENC[AES256_GCM,data:7Q==,iv:Aq4ZkcxH9d1AgOM8vUQAWgE07+cycmY9rkxkyDxEv4I=,tag:2bFjLvsAH8ia7Iew/pjKrw==,type:str]
  CONFIG_CONTROL_MEM: ENC[AES256_GCM,data:YJmNTQ==,iv:FReGn0gK2GQv0TtCz0bRdIgDs/NdYD04/z8HR16Dc+w=,tag:RYN6cCIzVPFKsteYPKMKFQ==,type:str]
  CONFIG_CONTROL_DISK: ENC[AES256_GCM,data:9EJZ,iv:cMD4Ztn8BldAfR7R+bV08j2kA5cB8fxwrctk4zw6MgY=,tag:4yom8kY9ooOHPynCFMIzOQ==,type:str]
  CONFIG_WORKER_CPU: ENC[AES256_GCM,data:ZA==,iv:313vNFyS34r3Z5J9SUGQX5LO0uZfdw9AIxhWab4cfz8=,tag:3tqY+RSOXikBjR136zAqvQ==,type:str]
  CONFIG_WORKER_MEM: ENC[AES256_GCM,data:EqL1tw==,iv:Oxag67HhhkmoQzCt/5DWczA9f1bKOeiIANOXpds7lSA=,tag:uIymA4Ixn4EkArq4/ibFMw==,type:str]
  CONFIG_WORKER_DISK: ENC[AES256_GCM,data:bBYS,iv:jTCxT55hxckWzganJc+akcGrOMGF02VB775Xj7aZV9s=,tag:fKN5YJ/q6o18WlVTChIvkQ==,type:str]
  CONFIG_TZ: ENC[AES256_GCM,data:uhVeyX7OR9NfZ6HjSEASeA==,iv:JRl0M8hxmZ7VjWi5l9usavvBX+w9NvGDNhh2Dk1Y3+0=,tag:6l7MeNxT2JAgjzjjSWxDAA==,type:str]
  DNS_CLUSTER_DN: ENC[AES256_GCM,data:Hj5vtTqqPEBFe3qvCQ==,iv:ncVuHuyNEpwfCG2mNb6QlRoPxxCQi76PUwlHrXIVMPc=,tag:g70HEJvZL2bp2vU+NXW3zg==,type:str]
  DNS_CONTROLPLANE_FQDN: ENC[AES256_GCM,data:JtVcmPCjiLH1sFTDy9AYNpgGIEUriooPgNY=,iv:owjNIls5NyWv0J1SzBYfGnoHn6GeH8lnrXqToFyqnZ8=,tag:wsyOL0rGUXKcYMZGXy34PQ==,type:str]
  IP_CLUSTER_VIP: ENC[AES256_GCM,data:uTQJK2hcZTexZVIN,iv:/FuBOn8NSUWhjAoqeKT/FIjtC3Nm2hdOpTQnrtropaU=,tag:A2cvbj3x+Gfsh/iv49OvFA==,type:str]
  IP_POD_CIDR_V4: ENC[AES256_GCM,data:uHJkAK9rhuDdsZI2,iv:gLUilY6a1WgtkpFqI2VLTLdqaK+b1X3cvzxXjjY1LQs=,tag:pg7euATu3U3CSQMBdKSbdA==,type:str]
  IP_SVC_CIDR_V4: ENC[AES256_GCM,data:6JJILXV01DCd0c6bqw==,iv:NOIRZMAh5Yi/fcpUNHIWmjMp1Z5JR+tC1YW3W8eYA9M=,tag:w6EfBUIsBEBZ49D+wF4uZw==,type:str]
  IP_CONTROL_01: ENC[AES256_GCM,data:8XbSQcAk3RDUHp9d,iv:72tWpg9614oNJeDDv5ODGUP89l6HFSCR0pWm5Y8eP80=,tag:atVdBR86wIhurpWJxLJ7IQ==,type:str]
  IP_CONTROL_02: ENC[AES256_GCM,data:T3Ma86dApGf+6K7C,iv:1G5vkvghq7nLECZRR3ODfeD3+hM0E2fG3mQKLZTvf5c=,tag:nwJrZeT5PPl/sGK5eroLUg==,type:str]
  IP_CONTROL_03: ENC[AES256_GCM,data:utrzIxvP0GjYSatW,iv:vN7j3O+sJWWRhfcok6paOow/iZVrCAZ5K3D9lA+u/zo=,tag:wIjaVyepC7EEOprMt4LUsg==,type:str]
  IP_WORKER01: ENC[AES256_GCM,data:esqE62yyFBGERFvH,iv:7QK6apTtOrsmtJ2lh6YK9baL+1KDR8Dv7SJ9eU8ktXU=,tag:y4XFELcuE7/NrCSJUQEdgg==,type:str]
  IP_HOME_DNS_1: ENC[AES256_GCM,data:Eon/gRZN5c77VwCL,iv:UelZt5yStdMGta1HPNY9m7sSlEafLYEHnpsSuIt5OHk=,tag:MXrbXtWVuZtBhvDX0WbAHg==,type:str]
  IP_HOME_DNS_2: ENC[AES256_GCM,data:V4UA4003YLqYesE=,iv:PH4+/cEGOSE5SO0a7miZmMY/Hco0JO2FHQ89XsWZwrI=,tag:4ZZ1+QMh9ZPo4bZba+OFaw==,type:str]
  IP_GATEWAY_K8S_VLAN: ENC[AES256_GCM,data:1nL1/WXmXeiKMpU=,iv:FHhX2WXW21l6XL+/fnVLSWT327HsrFyMU0rS8oCT7dU=,tag:hHpfNWBtB3++QMJIg2loqA==,type:str]
  IP_NTP_SERVER: ENC[AES256_GCM,data:ifcxjAjyw3LC3to=,iv:2lXy2HwixTkNa8nBkXF/zEsJe9V0WfeCw3JVpsQtgnA=,tag:wnZ6k0icM/jQNROGsQ70yQ==,type:str]
  IP_LB_CIDR: ENC[AES256_GCM,data:go+qwiLEcLHy99I=,iv:DTSHPVnRMdPQbnZ65LMKFB4OhRPin6fSI7LWba6X0aI=,tag:NB98Pu1K3V9tP+Oc1GB5+Q==,type:str]
  GOVC_INSECURE: ENC[AES256_GCM,data:Ql773g==,iv:WMBiICC9BEyWRKz0H3CFd3Ds2kIqUffEXj0ckpRMggg=,tag:ojJB019LJjJilgxHe+9pzQ==,type:str]
  GOVC_LIBRARY: ENC[AES256_GCM,data:DIXX87w=,iv:bGwu2dBqE+wrxZC9IC0oYiSKKBxOXGWIOytx6J8FaPE=,tag:2oXJLBP5h780+gr3AGU1HA==,type:str]
  GOVC_DATACENTER: ENC[AES256_GCM,data:58saHHyl6AIVdj/60YUI,iv:gQ2Eawzk9XWdjlPHD2aE/M8rIvAhSJeaa6EW+B2jVHo=,tag:X6BWPMDu79NlUIfP4amozA==,type:str]
  GOVC_RESOURCE_POOL: ENC[AES256_GCM,data:gNYnwTky1RmVaVdOGiQ98ehFxGNdUgo=,iv:ChtwWIV9J4+TSb02SaegeL5MuV673UHoIHibiFE+nzg=,tag:rYDPpJ7gd7q8m59TvcMcLw==,type:str]
  GOVC_DATASTORE: ENC[AES256_GCM,data:kmhru17Z9SN5IiWQYw==,iv:nuxiwz3pRs9+/mrrqhL/Xssdyt3V/3VAf3hAztVLmRM=,tag:VSbTg45jG3Ta7Ngf2s6mxg==,type:str]
  GOVC_NETWORK: ENC[AES256_GCM,data:8Ujc,iv:UklZepHNjN0aM2TZKNSU0prKdh0qffkkn3LwSQbPppg=,tag:XSHKIPFhYH7b+UWOakHrmw==,type:str]
  ASN_ROUTER: ENC[AES256_GCM,data:RBPSRuo=,iv:Cp40zctZwUNgFLjYoh39H+7Pm+jm+G6k/nsx+KqWq28=,tag:KMTbxXs1lQAvyaNGoch9UA==,type:str]
  APP_DNS_HUBBLE: ENC[AES256_GCM,data:1jC9BrYJfasHfCQkcOFMf64tNd0Ffz8=,iv:diY6/D+5SpgD++HS92Z120Q2WUh1yWlnJ7bhaU5CyQo=,tag:bLHjG2+WNjePlIsQY3fn8w==,type:str]
  APP_IP_NGINX: ENC[AES256_GCM,data:X/37AxEAm47d,iv:hR3rQ+hbV6yKl5xYhN+9Piacj8xk5/7cbmXeToWDfk0=,tag:mKYfC1XAQMKvfjo59unTKg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1skatly42g7vng3twta22kdlvzg98p3p5zk7rzn285pncxkzzu3usvp7gvh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcmgrUmtlOGpiZWNUNE8x
        UzN6bHVCOVVhL0liZ0tWY25vNitFOWVROURzCmdhOXdNb1poNVNuYmJMdGhub0Rh
        Uml0V1JkU1NiMnc3Q09kWW56QW1PUHcKLS0tIFQ3dGhDYkpBRmpNQWd6a0dyc1Ey
        aGFWYTJtTGhJWVlCaTQrRkRscEJ6c00KnEoFFOU1WlffI8GMPyTAz3ctvZPx4lrI
        UaUrfhk1fcCsLPZdrDK8bAZ/dOLoy0Nt2TwaRCAEWk+NLyUumZxQ+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2023-12-07T15:43:51Z"
  mac: ENC[AES256_GCM,data:U3iyNW7IcEp7AA4TczmKNMyxzDhp4WWaG4gBWFaLZR31OtjTPALrQIQeADH1dx9JKvrG+6CqfijT6XJ6vUoLIjawLWDxBTZNg1SbWRI0u68m9PSnFr3zjCQkDxhBs05Jn9xNwJPozFGuNvuU9Ya7sCaHzUBK3CqF0HrjFNKoWOA=,iv:JmjUXVWVrw3xagPla5xEOKs5FwDj2BC3YfrJrcwa6Dc=,tag:FlH0M8gjsUvU8As3D4eTqA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
