apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: kube-prod-vars
stringData:
    OP_VERSION: ENC[AES256_GCM,data:ESrgL671yQ==,iv:F/Y3V+1m0fEmjmZwGijNd8WAr0u1E0yMlKCkPNQoNDU=,tag:hWUVWEG4b1QKRWylFmlclA==,type:str]
    TALOS_VERSION: ENC[AES256_GCM,data:WPmzXUMT,iv:tJFfTVOL3sXEgzlkZHqRCrXkn0Z4keoPjbMtYmmp/2E=,tag:I0EptATzssvVIF+3kKpukA==,type:str]
    KUBERNETES_VERSION: ENC[AES256_GCM,data:gC4hXrQR4g==,iv:9xkLhFgLWZb0vz8++5chAL0vXzGN6cEVAZxw4QqHDg4=,tag:2a4ui/RV4nWnoa8R9e8Pyw==,type:str]
    CLUSTER_NAME: ENC[AES256_GCM,data:khfT7GVESync,iv:hu/Wh3xamsNCXMJtD/sMx8nPNJ/9rOk75B1D7wV+XyI=,tag:uhz+EzZCvBgOZFdwQRk57A==,type:str]
    CONFIG_CILIUM_CLUSTER_ID: ENC[AES256_GCM,data:Tw==,iv:S9YtuEwvXWNq/IOA+l8nLg7HZgKccC+Dk97fGNfPM4Q=,tag:Io8coGykGvSvqSq5ZqMTRA==,type:str]
    CONFIG_CONTROL_CPU: ENC[AES256_GCM,data:Pg==,iv:r3Eu0PuIMyBul2Xra99EGXjomuMim1q8MiYVjzuWnro=,tag:TUp9c5HbPouALpfS1UcqiA==,type:str]
    CONFIG_CONTROL_MEM: ENC[AES256_GCM,data:SdixSA==,iv:mFA+pB51IW1JsZPJUxu+OIT/S5KQ1MOpeQV21wPJoU4=,tag:ty3fxFeJ68kuGBBxIDz7nA==,type:str]
    CONFIG_CONTROL_DISK: ENC[AES256_GCM,data:eXFt,iv:pYs7SZ91Z+wg3Bcfown8ZpQK6+v+h35/yGhmw69ibgI=,tag:ucRM7UQk/c/pheomu836fg==,type:str]
    CONFIG_WORKER_CPU: ENC[AES256_GCM,data:4w==,iv:sVLkzEIPrs4ewdKfMrBZ5Bhgv+ODXfWbAa+KKp50Ecs=,tag:MeQRAMgu2Sm5Hgg3KOfIdw==,type:str]
    CONFIG_WORKER_MEM: ENC[AES256_GCM,data:vnE/pQ==,iv:iYRjAD73OYhdgUxfTGxiTALZTcz9nlwOC+U1S3wzuzU=,tag:Igoh5fvL/L4XTUQTNTXUew==,type:str]
    CONFIG_WORKER_DISK: ENC[AES256_GCM,data:g6PF,iv:hzjB+pqvnY3e4zIeY6aS4OD8S30J3Vr5U+Hz1svuxSU=,tag:+0bqF/TzoiSfXHkEgossHA==,type:str]
    CONFIG_TZ: ENC[AES256_GCM,data:fE8M+VdLAADDa309eE3W8A==,iv:bnvY0xI2PXShOOmaLKXhqBXtU6IQZgBgds1Vu23hZaA=,tag:E2lrDpd7LykpFXU8ulqqYA==,type:str]
    DNS_APP_HUBBLE: ENC[AES256_GCM,data:FJ4jsbJgQN+VnMIZuPjv60a6apJ+tIc=,iv:3J5BD3KbssleYCViFk+g4FTJWLBmG8gBUjS+u97FImQ=,tag:fWPKKP0y6eX4Y+PdB5wevA==,type:str]
    DNS_CLUSTER_DN: ENC[AES256_GCM,data:eQ57smW5Xk8pdepeyw==,iv:LRHpM2OI9vAUQBldvwKSaFsLP3SCtt0q5KBOwqdP2ac=,tag:bSOTajJpGL2z4NLPLJkZfQ==,type:str]
    DNS_CONTROLPLANE_FQDN: ENC[AES256_GCM,data:T26W+lUQGJO0oH/ss8Y+EwpX3Ysfgg9bMLI=,iv:sCvtYmbTgBU0Jd7MNs51r7XodOG4YXIUAa/BMcbPfL8=,tag:3utAU1olLXunhVUNt+Dy6w==,type:str]
    DNS_HOME_ROOT: ENC[AES256_GCM,data:Z5goej4eA/m3CjDKaTDDsg==,iv:67zfTCC70MZfmuojEoY9HDq+9eeugICBPvpKW+ayM5Q=,tag:1G8+RdKzwJcvjSa6kcdoiA==,type:str]
    IP_CLUSTER_VIP: ENC[AES256_GCM,data:qpKysbHhtrY9dQKU,iv:YQ4SEXuD4W/augCdOG5SUgvmXUnyNuXn81KTHaoD8f8=,tag:PukYccYJOWcQrISLTZcuvQ==,type:str]
    IP_POD_CIDR_V4: ENC[AES256_GCM,data:yruj7AXby/eCHuoI,iv:EXqvE0wPu983cOSNHneli700YtO/Uw5p/cy3C6POZjo=,tag:NCQjlioUjGE24FeNQ/9fBQ==,type:str]
    IP_SVC_CIDR_V4: ENC[AES256_GCM,data:7XWLkMsk0OE7JWM8Zg==,iv:JYW6BFOobsLZC4NLMOQI6t2TJTGUKDnk+8w1eP6GqhY=,tag:5vSNPZtsut+emeO3ZIdInw==,type:str]
    IP_CONTROL_01: ENC[AES256_GCM,data:0mzCCn/dyRgD/bsN,iv:6Jli+ZdNc1HVls9c7l1g04VoILbPSWbPDVtlHzrb7fE=,tag:QxpSsq0+ybON3xPB52+rjg==,type:str]
    IP_CONTROL_02: ENC[AES256_GCM,data:ka5mKY8CfIb2oIjS,iv:qFZ1Rehnb3pOP06JV6pZIY4VroIlJTWYfFWEGEkL1Tk=,tag:6AuXytkq7K4UVgGmu5QohQ==,type:str]
    IP_CONTROL_03: ENC[AES256_GCM,data:S4IAX7XRzARg2Y+V,iv:skTQTePSipcYjdqCM2bcNLoz4Faicj4QhXnjG8l6H6s=,tag:ijlmNe4uMx2PduUFXPNvZw==,type:str]
    IP_WORKER01: ENC[AES256_GCM,data:e+rvZxe5XT+nbSmI,iv:h1KT4BQibmUnu6+tBoE60GrDZfhoyz2UXu71EdU9EFA=,tag:jPK68KaRZl1gKsYrya2oBw==,type:str]
    IP_HOME_DNS_1: ENC[AES256_GCM,data:PtNmqi4Q3ajMgTeT,iv:2bunIX8YC+rQ3D28pIIWW6ynvW8/phKk7bQoAZeaycU=,tag:x1sE1oom8RnduZ8jktlGxQ==,type:str]
    IP_HOME_DNS_2: ENC[AES256_GCM,data:4yF8fsYDrLwJ/6A=,iv:8QG5PPkssNNjA2ndfjREl3De2THqCSX2OCwIYJXznhk=,tag:Ns9vGEIOXF10U+v9Xj2S8w==,type:str]
    IP_GATEWAY_K8S_VLAN: ENC[AES256_GCM,data:W7u5aEqHZWmKP2I=,iv:MqwFEp64rquCyCFq1B+dGaguos8yFzYC/Xizx5tFKE0=,tag:WOncuwOoFG6KW8TlNMFtVA==,type:str]
    IP_NTP_SERVER: ENC[AES256_GCM,data:UtRucZkhJFYQRhE=,iv:G/PRQDqJ5QpYO43Z48+4tbaKsGaD0A5JW+0JHGViym4=,tag:vknLr4PsiisOjKBBWhGxQA==,type:str]
    IP_LB_CIDR: ENC[AES256_GCM,data:9MUR2UDzW7O6FY0=,iv:5h+r4Jin9S6oWEi/Qmu6qy4mZo1A+hnYhqxXWXrHvBM=,tag:n+HHWdPGRKLfVbgkEqSVHA==,type:str]
    IP_APP_NGINX: ENC[AES256_GCM,data:KgPQ94wea8OK,iv:kL8mx/LDYKxjROaEq+RJ0X2HOIHVX81CF4UIHbhWQ9A=,tag:eqJSDsv7+GsFnpIFh/Rd/g==,type:str]
    GOVC_INSECURE: ENC[AES256_GCM,data:RuVNzA==,iv:dt2HvbNEEIsfW0ahjGw1LyMssEByU6DJiczSK5KdHrM=,tag:s+OerUTv7HUsxbMYyKYnLA==,type:str]
    GOVC_LIBRARY: ENC[AES256_GCM,data:9fM6cXI=,iv:utcXQfIiNoF1dDeJ4GAjOot9KRvnblG6fcz5pih9HdU=,tag:eEJ0Mryxe3Ih0nKuKoiGaw==,type:str]
    GOVC_DATACENTER: ENC[AES256_GCM,data:IR3ApFTFtx7MQr84Il9F,iv:TekfHkeVEzQlTuf/nlh7pSgvZhU2vqSfSXY1y8ufI5k=,tag:lXTeqHihlYfwDwVUTX0DMA==,type:str]
    GOVC_RESOURCE_POOL: ENC[AES256_GCM,data:CKUXkq7QnCCQbHEEeB65dv5KZ8WWIg4=,iv:W2oeCD5jIF4ztVkHl++EhamTh4cHFW6teJFii4fU9tc=,tag:K3l+GE/+395kHMu3dixOaA==,type:str]
    GOVC_DATASTORE: ENC[AES256_GCM,data:QIuPvuMjyWG/0R3Uzg==,iv:ZugHPDb5o3HDNbHh23Ud+U3CYaYYAo4x9X/c+jBOwXA=,tag:O/p0eF6qsOjLELoZU/arnQ==,type:str]
    GOVC_NETWORK: ENC[AES256_GCM,data:x8v+,iv:JHQ4cqiD9w+cC39I9G85FLNRWLU3p2R1od4Aop8rYo8=,tag:MqQNpKpVPafXpB0grYdYTA==,type:str]
    ASN_ROUTER: ENC[AES256_GCM,data:8ghWSho=,iv:hk33L9fq0oKawEDNmnBXnvDrrRrxBMHvyPROGldWTAM=,tag:rZ/pCfL1WMXjCavmtchTUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1skatly42g7vng3twta22kdlvzg98p3p5zk7rzn285pncxkzzu3usvp7gvh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2aEphT2w4WnFrdjUzYlJY
            a2Q2U2E2U051R1pHaDVqUzErMGJ3SGNOaUJjCklSaFpEWm1OUFVqczhIeUF6RzlY
            NXhwb0VjUEpYcytpUTVOYUFVZmVMZWcKLS0tIGRxTmh1NDNIWWQreGtPSWJoNG82
            a05IbExpU3haMFFHaEo3a3F2akxBLzQKMhI2ueEE9+KFyKgAiGqvYnYc3VTK1TRK
            driPgRhtOIhFUv79pP0tMG5KA2MzLbrOdtdHgZYufh7p4haXn3q15Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-12T12:45:30Z"
    mac: ENC[AES256_GCM,data:ZjfxOEcq5jV6nWw7vSM3wQjizTXEbgcGTNKgLDYLVoM9iUDcjevspiJPqmaWyV8DHFkmNj8oy/Z0fKID+RTwMdjo/dCKlRd79/g1t/EZ9iqgupWO/EI2yslVsEp7BnLVOBDNi/FeMDxZfpVJ2hBAT49slpzO+ubUpTbY/06/N2s=,iv:nhrRHsLJbh08fpjFvKKuELLYU39SSRrOyCgCOtRx/pg=,tag:t2JuJ/cOG2T83UywLMrfXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
