---
# yaml-language-server: $schema=https://kubernetes-schemas.raspbernetes.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-core-kubelet-csr-approver
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/kubelet-csr-approver/app
  dependsOn: []
