---
version: "3"

tasks:
  install:
    cmds:
      - kubectl apply --server-side --kustomize {{.ROOT_DIR}}/kubernetes/bootstrap/flux/

  get-all-watch:
    aliases: [ga, fga, getall]
    cmds:
      - viddy -n1 flux get all -A || watch -n1 flux get all -A

  cantWait:
    aliases: [cw]
    vars:
      NS: '{{ .NS | default "flux-system" }}'
      KS: '{{ .KS | or .KS (fail "Missing `KS` environment variable!") }}'
    cmds:
      - kubectl patch ks -n {{.NS}} {{.KS}} --type merge -p '{"spec":{"dependsOn":[]}}'
      - kubectl patch ks -n {{.NS}} {{.KS}} --type merge -p '{"spec":{"wait":false}}'
