---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard
spec:
  secretName: wildcard-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: ${DNS_PUBLIC_ROOT}
  dnsNames:
    - ${DNS_PUBLIC_ROOT}
    - "*.${DNS_PUBLIC_ROOT}"
