---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: "ingress-nginx-helm-values"
    namespace: "ingress-nginx"
    files:
      - common-values.yaml
configurations:
  - kustomizeconfig.yaml
resources:
  #- netpol.yaml
  #- default-backend.yaml
  - hr-internal.yaml
  #- hr-external.yaml
  #- hr-public.yaml
