---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
  namespace: external-secrets
spec:
  provider:
    onepassword:
      connectHost: ${OP_CONNECT_HOST}
      vaults:
        ${OP_CONNECT_VAULT}: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: external-secrets
