---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-ingress-nginx
  namespace: flux-system
  labels:
    prune.flux.home.arpa/disabled: "true"
spec:
  targetNamespace: ingress-nginx
  path: ./kubernetes/apps/ingress-nginx/app
  dependsOn: []
